#Fill here the Google Maps API keys for your application
#In this sample:
#For development and test, we have only one possible host (localhost:3000), so there is only a single key associated with the mode.
#In production, the app can be accessed through 2 different hosts: thepochisuperstarmegashow.com and exmaple.com. There then needs a 2-key hash. If you deployed to one host, only the API key would be needed (as in development and test).
# 

development:
 localhost: ABQIAAAAzMUFFnT9uH0xq39J0Y4kbhTJQa0g3IQ9GZqIMmInSLzwtGDKaBR6j135zrztfTGVOm2QlWnkaidDIQ
 192.168.134.197: ABQIAAAAV-_4T6871IiMUJ74QnQnsRTeSdU9_rW6GFq-UHSTO-cTsPEIQRQND4_fFF3w3f2diTB2Qlv4MhfZXQ

test:
 ABQIAAAAzMUFFnT9uH0xq39J0Y4kbhTJQa0g3IQ9GZqIMmInSLzwtGDKaBR6j135zrztfTGVOm2QlWnkaidDIQ

production:
 bonoboaward.com: ABQIAAAAV-_4T6871IiMUJ74QnQnsRQngbj3iyY4WxaU55954I0suuTHIRQfyChh8QOkpomPYzTn9Z5Wmz68xg
 7voor11.com: ABQIAAAAV-_4T6871IiMUJ74QnQnsRTpfLsf8J8S0jGabvnPaIJSyTU2gRT0DtGi8hO03f6xPa17jqKhdp2d2A
 webserver.vda-groep.nl: ABQIAAAAV-_4T6871IiMUJ74QnQnsRT2NOEt1BPU-PJxJ1YzPGzvDGRVFxT62UWmdJe-5fZKGuXlGU1Q636wfQ
 kop.pampus-lollebroek.nl: ABQIAAAAV-_4T6871IiMUJ74QnQnsRQl1QJW5NWo6XPtQIznZVasf1KtqxT4fAE2imLfN6ejNWXSSMYIsNfjPg
