twitter:
  read_url: http://twitter.com/statuses/user_timeline/optocht.xml
  write_url: http://username:pass@twitter.com/statuses/update.xml
  development_uri: localhost:3000
  test_uri: localhost:3000
  production_uri: yourdomainname.com